### ISSUE TITLE
Extension doesn't work?

### ISSUE THREAD

**Issue by dev-jlb** [madskristensen/Shifter#12]
**Describe the bug**
This extension doesn't work for me.  I tried it in Visual Studio Enterprise 17.4.4, and in Visual Studio Professional 17.2.x.  DO you have suggestions on how to troubleshoot why it isn't working?

**To Reproduce**
1. Go to code editor
2. double click to highlight a variable
3. Press Ctrl+Alt+Up
4. Nothing happens

**Expected behavior**
Extension to work.

**Screenshots**
n/a

**Additional context**
I checked TOols > Options > Environment > Keyboard and made sure I saw entries for Shifter.

**Comment by lordfanger** [comment]
What variable are you highlighting?

**Comment by dev-jlb** [comment]
Example: 
![image](https://user-images.githubusercontent.com/101914968/216710551-7f3de912-aeb0-4f36-aa47-b49f2d747b05.png)

**Comment by lordfanger** [comment]
From your screen it looks highlighted but document is not active (focused). Extension works only on active document so it doesn't shift text on hidden window. :)

(left inactive|right active)
![image](https://user-images.githubusercontent.com/17590847/216758449-6601fc5a-dc87-4b15-af0c-14cd02317ea3.png)

Have you checked the keyboard shortcuts are not overriden by something? If you set `Use new shortcut in` to `Text Editor` and `Press shorcut keys` to desired shortcut. Is command inside `Shortcut currently used by` the Shifter one?
![image](https://user-images.githubusercontent.com/17590847/216758643-f6e38bfe-7f90-4145-be58-b2f023f74b3e.png)

**Comment by dev-jlb** [comment]
> From your screen it looks highlighted but document is not active (focused). Extension works only on active document so it doesn't shift text on hidden window. :)
> 
> (left inactive|right active) ![image](https://user-images.githubusercontent.com/17590847/216758449-6601fc5a-dc87-4b15-af0c-14cd02317ea3.png)
> 
> Have you checked the keyboard shortcuts are not overriden by something? If you set `Use new shortcut in` to `Text Editor` and `Press shorcut keys` to desired shortcut. Is command inside `Shortcut currently used by` the Shifter one? ![image](https://user-images.githubusercontent.com/17590847/216758643-f6e38bfe-7f90-4145-be58-b2f023f74b3e.png)

Apologies for the late response.  

The not active/focused is an artifact of opening the WIndows snipping tool to capture a screenshot.

But, your second screenshot led me to what I think is the root cause.  I think Remote Desktop was intercepting the Ctrl+Alt+Up combination.  When I tried typing that combination in the "Press shortcut keys" box, nothing was displayed.  But, if I entered a key code combination (e.g. Ctrl+Alt+=), it was recognized, and the extension worked as expected.
