### ISSUE TITLE
Shifter does not honor casing for named colors in XAML

### ISSUE THREAD

**Issue by IndianaGary** [madskristensen/Shifter#2]
### Description
I was able to install Shifter and Color Preview mostly so that I could use the extensions with XAML. It appears that the named Color values are always provided in lower case, which is more appropriate for CSS. My suggestion is that Shifter be sensitive to whether or not it is running on a XAML file and to use Pascal casing for the color names.

### Steps to reproduce
1. Install Shifter. Install Color Preview or use the experimental "Show inline color previews" on the XAML Miscellaneous section under the Text Editor XAML language.
2. Open a XAML file that contains Color specifications. I use the Xamarin Forms and Maui incarnation. A good file to choose is the App.xaml file, since it is a common place to specify Color definitions.
3. Use Shifter's Ctl-Alt-Up or Ctl-Alt-Down to toggle color values.
4. Note that named colors are all lower case.

**Expected behavior:** [What you expected to happen]
Named values should be lower case for CSS and Pascal case for XAML. Other file extensions may honor different rules.

**Actual behavior:** [What actually happened]
Named colors are all lower case regardless of file type.

**Comment by lordfanger** [comment]
Hi @IndianaGary,
can you try the version 1.0.25 from [https://www.vsixgallery.com/extension/Shifter.2788249e-f649-4ef6-a0e4-e390ccdbe588/](url)?

**Comment by IndianaGary** [comment]
Will do, thanks!

**Comment by patricksadowski** [comment]
@lordfanger Can you close this issue please?

**Comment by lordfanger** [comment]
I can but I don't know if it works or not. I don't use XAML anywhere.
